version: '3'
services:
  todo-list:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "82:3000"
    volumes:
      - "todo-db:/etc/todos"
    networks:
      - default
volumes:
  todo-db:
